### ISSUE TITLE
Pre-processing of landsat_scd dataset

### ISSUE THREAD

**Issue by YuhangZh** [ggsDing/SCanNet#11]
Hi, you mentioned in your paper that when working with the Landsat dataset, excluding those samples obtained by spatial augmentation operations (including flipping, masking, and resizing), and using only the original samples for training and testing. I would like to ask what is the intention of doing this and what is the impact on the experimental accuracy.

**Comment by ggsDing** [comment]
Hi. The reason is that I think these operations are only augmentations, which do not produce samples.
And in my opinion, doing all the augmentations during training iterations would be more efficient and effective. You can set random variables to decide the augmentation in each training iteration. This will expand the actural sampling space.
